Repository Project-FitLoop/FitLoop-BE, pull requests merged in 2025-05, with the labels that each got.

#26 [FEATURE] Redis 키와 값 수정
  .gitignore
  src/main/java/fitloop/member/controller/ReissueController.java
  src/main/java/fitloop/member/jwt/CustomLogoutFilter.java
  src/main/java/fitloop/member/jwt/JWTFilter.java
  src/main/java/fitloop/member/jwt/LoginFilter.java
Labels: ✨ Feature

#28 [FEATURE] 상품 상세 페이지 구현
  src/main/java/fitloop/config/SecurityConfig.java
  src/main/java/fitloop/member/repository/ProfileRepository.java
  src/main/java/fitloop/product/controller/ProductController.java
  src/main/java/fitloop/product/dto/response/ProductDetailResponse.java
  src/main/java/fitloop/product/repository/ProductCategoryRelationRepository.java
  src/main/java/fitloop/product/repository/ProductImageRepository.java
  src/main/java/fitloop/product/repository/ProductTagRepository.java
  src/main/java/fitloop/product/service/ProductService.java
  src/main/resources/data.sql
Labels: ✨ Feature, 📬 Api

#30 [FEATURE] 인기상품 및 카테고리별 상품 조회 로직 구현
  src/main/java/fitloop/product/controller/ProductController.java
  src/main/java/fitloop/product/dto/request/ProductRegisterRequest.java
  src/main/java/fitloop/product/dto/response/ProductResponse.java
  src/main/java/fitloop/product/entity/CategoryEntity.java
  src/main/java/fitloop/product/entity/category/BottomCategory.java
  src/main/java/fitloop/product/entity/category/MiddleCategory.java
  src/main/java/fitloop/product/entity/category/TopCategory.java
  src/main/java/fitloop/product/repository/ProductRepository.java
  src/main/java/fitloop/product/service/ProductService.java
  src/main/resources/data.sql
Labels: ✨ Feature, 🔨 Refactor

#31 [FEATURE] 상품 상세 및 장바구니 로직 구현
  src/main/java/fitloop/cart/controller/CartController.java
  src/main/java/fitloop/cart/dto/response/CartItemResponse.java
  src/main/java/fitloop/cart/entity/CartEntity.java
  src/main/java/fitloop/cart/repository/CartRepository.java
  src/main/java/fitloop/cart/service/CartService.java
  src/main/java/fitloop/config/SecurityConfig.java
  src/main/java/fitloop/member/controller/ReissueController.java
  src/main/java/fitloop/member/entity/RefreshEntity.java
  src/main/java/fitloop/member/jwt/LoginFilter.java
  src/main/java/fitloop/member/oauth/OAuth2SuccessHandler.java
  src/main/java/fitloop/member/repository/RefreshRepository.java
  src/main/java/fitloop/member/service/UserService.java
Labels: ✨ Feature, 📬 Api, 🔨 Refactor

#33 [FEATURE] 로그인 어노테이션 구현
  src/main/java/fitloop/config/WebMvcConfig.java
  src/main/java/fitloop/member/auth/Login.java
  src/main/java/fitloop/member/auth/LoginInterceptor.java
  src/main/java/fitloop/member/auth/MemberIdentity.java
  src/main/java/fitloop/member/auth/VerifiedMember.java
  src/main/java/fitloop/member/auth/VerifiedMemberArgumentResolver.java
  src/main/resources/data.sql
Labels: ✨ Feature, 🚨 Hotfix

#35 [FEATURE] Kafka 연동 및 Swagger 설정 반영
  README.md
  build.gradle
  src/main/java/fitloop/config/SecurityConfig.java
  src/main/java/fitloop/kafka/KafkaConsumer.java
  src/main/java/fitloop/kafka/KafkaTestController.java
Labels: ✨ Feature, 🌏 Deploy, 📃 Docs

#36 [DEPLOY] main 브랜치 병합
  .gitignore
  README.md
  build.gradle
  src/main/java/fitloop/cart/controller/CartController.java
  src/main/java/fitloop/cart/dto/response/CartItemResponse.java
  src/main/java/fitloop/cart/entity/CartEntity.java
  src/main/java/fitloop/cart/repository/CartRepository.java
  src/main/java/fitloop/cart/service/CartService.java
  src/main/java/fitloop/common/exception/GlobalExceptionHandler.java
  src/main/java/fitloop/config/RedisConfig.java
  src/main/java/fitloop/config/SecurityConfig.java
  src/main/java/fitloop/config/WebMvcConfig.java
  src/main/java/fitloop/kafka/KafkaConsumer.java
  src/main/java/fitloop/kafka/KafkaTestController.java
  src/main/java/fitloop/member/auth/Login.java
  src/main/java/fitloop/member/auth/LoginInterceptor.java
  src/main/java/fitloop/member/auth/MemberIdentity.java
  src/main/java/fitloop/member/auth/VerifiedMember.java
  src/main/java/fitloop/member/auth/VerifiedMemberArgumentResolver.java
  src/main/java/fitloop/member/controller/ReissueController.java
  src/main/java/fitloop/member/entity/RefreshEntity.java
  src/main/java/fitloop/member/jwt/CustomLogoutFilter.java
  src/main/java/fitloop/member/jwt/JWTFilter.java
  src/main/java/fitloop/member/jwt/LoginFilter.java
  src/main/java/fitloop/member/oauth/OAuth2SuccessHandler.java
  src/main/java/fitloop/member/repository/ProfileRepository.java
  src/main/java/fitloop/member/repository/RefreshRepository.java
  src/main/java/fitloop/member/service/UserService.java
  src/main/java/fitloop/product/controller/ProductController.java
  src/main/java/fitloop/product/dto/request/ProductRegisterRequest.java
  src/main/java/fitloop/product/dto/response/ProductDetailResponse.java
  src/main/java/fitloop/product/dto/response/ProductResponse.java
  src/main/java/fitloop/product/entity/CategoryEntity.java
  src/main/java/fitloop/product/entity/category/BottomCategory.java
  src/main/java/fitloop/product/entity/category/MiddleCategory.java
  src/main/java/fitloop/product/entity/category/TopCategory.java
  src/main/java/fitloop/product/repository/ProductCategoryRelationRepository.java
  src/main/java/fitloop/product/repository/ProductImageRepository.java
  src/main/java/fitloop/product/repository/ProductRepository.java
  src/main/java/fitloop/product/repository/ProductTagRepository.java
  src/main/java/fitloop/product/service/ProductService.java
  src/main/resources/data.sql
Labels: 🌏 Deploy

#38 [DOCS] 리드미 ERD 추가
  README.md
Labels: 📃 Docs

#40 [HOTFIX] Refresh 토큰 만료일자 타입 LocalDateTime으로 통일
  src/main/java/fitloop/member/controller/ReissueController.java
  src/main/java/fitloop/member/entity/RefreshEntity.java
  src/main/java/fitloop/member/service/UserService.java
Labels: 🚨 Hotfix
